### ISSUE TITLE
URGENT: Ben is hurt

### ISSUE THREAD

**Issue by stephenmesa** [joropeza/isbenhurt.com#20]
His left pec is hurt, so the site should say `Yes`

Source: https://twitter.com/bepryor/status/1440346996217303050

**Comment by stephenmesa** [comment]
Can I get an SLA on this to give to my stakeholders please?

**Comment by joropeza** [comment]
Commit is pushed, build is green... smoke testing

**Comment by joropeza** [comment]
LGTM, closing incident
