### ISSUE TITLE
Make a yes page

### ISSUE THREAD

**Issue by stephenmesa** [joropeza/isbenhurt.com#4]
In the extremely unlikely case where Ben does indeed get hurt, we need a Yes page that we can show instead of our No page.

The Yes page should have a prominent "Yes" along with a panic button that displays a random (ideally Steelers-related) gif

**Comment by stephenmesa** [comment]
Here's a lo-fi mockup

![170908_214829](https://user-images.githubusercontent.com/1592038/30237102-8efe1ba4-94df-11e7-94e0-ca00a9c3c532.png)

**Comment by joropeza** [comment]
could that button -blink-?

**Comment by stephenmesa** [comment]
This has been resolved. http://www.isbenhurt.com/yes.html
